# Setup
title:        Wireless Network Reproduction
tagline:      Advanced network emulation tool to reproduce specific bad network condition on Mac OS.
baseurl:      "/wireless-network-reproduction"
url: https://github.com/FinalTheory/wireless-network-reproduction
zip: https://github.com/FinalTheory/WirelessNetworkReproduction/zipball/master
dmg: https://github.com/FinalTheory/wireless-network-reproduction/releases/download/v1.0/NetworkPerformanceAnalyze.dmg

# About/contact
author:
  name:       FinalTheory
  url:        https://github.com/FinalTheory

# Gems
gems:
  - jekyll-paginate

#Others
markdown: redcarpet
